### PR TITLE
Updated CSS properties for padding-block & inline (chrome warning)

### PR DESCRIPTION
**Pull request by SimpleIndian**
Hello, 
### I removed the Padding block and inline Properties because its showing a warning in chrome -

warning
 that makes it switch to default user agent style 
and update the regex to null because of an build error

### CODE REVIEW

**Comment by tomayac** [comment]
Thanks for the PR. In this case I chose to close it, since `padding-block` and `padding-inline` are supported by Firefox already and it looks good for Chrome to add support, too (it's implemented behind a flag already: https://developer.mozilla.org/en-US/docs/Web/CSS/padding-block#Browser_compatibility, https://developer.mozilla.org/en-US/docs/Web/CSS/padding-inline#Browser_compatibility).

If you want to override the user-agent styling, you can do so today, thanks to `::part()`:

```css
dark-mode-toggle::part(fieldset) {
    padding-block-start: 0.25rem;
    padding-block-end: 0.25rem;
    padding-inline-start: 0.25rem;
    padding-inline-end: 0.25rem;
}
```

Hope this works.

**Comment by tomayac** [comment]
Just to follow up, Chrome will ship these shorthands, see the [Intent to Ship](https://groups.google.com/a/chromium.org/g/blink-dev/c/E7f_WZOcTgQ/m/pbudXZNaAAAJ) thread (3 LGTMs means the API owners agree to shipping). Thanks again for the PR, hope the explanation why I chose to *not* accept it made sense.

**Comment by SimpleIndian** [comment]
Yes, That's Great to hear , I would love create new pull requests if i find any bug or want a feature, 
### **By The Way I use Dark-mode-toggle in my Website**
#### [mostlyflutter.dev ](https://mostlyflutter.dev) with some custom change

**Comment by tomayac** [comment]
Your site looks gorgeous, nice dark mode implementation!

**Comment by SimpleIndian** [comment]
Thanks, I really appreciate that

**Pull request closed without merging**
