### PR TITLE
Implement three-way appearance

### LINKED ISSUE #46: Apart from `light` and `dark`, add a `system` option
Is there any way (currently) or are there any plans on adding a system theme option that would just reflect the system and not override it? Or do I have to somehow make a custom one that clears the localStorage?

### PR DESCRIPTION
**Pull request by Haocen**
Close: https://github.com/GoogleChromeLabs/dark-mode-toggle/issues/46

It seems linter introduce some changes to files I didn't touch, let me know if it is not desired.

### CODE REVIEW

**Review by tomayac — APPROVED** [review]
LGTM, thank you!

After the merge, I'll replace the Yin Yang symbol with something else. I don't personally mind it, but some people might read something into it.

**Comment by tomayac** [comment]
Thank you very much, this is now released as [v0.16.0](https://github.com/GoogleChromeLabs/dark-mode-toggle/releases/tag/v0.16.0). `<3`

**Comment by Haocen** [comment]
Looks like there is a build failure, I'm not sure what I need to do.
The yin-yang is the only symbol I can find available from the public domain immediately, I agree it would be better if we can replace it with the half sun half moon symbol that was originally proposed.

**Comment by tomayac** [comment]
I think it's all fine now. `v0.16.0` just went out on npm and the [demo](https://googlechromelabs.github.io/dark-mode-toggle/demo/index.html) looks good to me. Thanks again!

**Pull request merged**
