### PR TITLE
Implement "slider" appearance

### PR DESCRIPTION
**Pull request by Haocen**
Problem Description
--
It seemed a slider may appeared to be more familiar to users, especially those who spend more time with their phone than anything else.
Inspired by: https://codepen.io/johan_p/pen/dyNgvRz

Change Implemented
--
Now a new "slider" apperance is added, please refer to demo below:

https://user-images.githubusercontent.com/10842569/201389130-3d749165-9995-47d7-a21b-acfb23896d62.mp4

Or take a look at [interactive demo](https://haocen.github.io/dark-mode-toggle/demo/index.html).

### CODE REVIEW

**Comment by Haocen** [comment]
Unfortunately the primary Email address associated with my GitHub account is not one from Google.

**Comment by tomayac** [comment]
Thanks for the PR. Note that for the Contributor License Agreement you don't need a Google email address. You can sign this with any email address.

For the actual PR: you don't need to modify the source code of the custom element itself, you can simply style the current "toggle" variant so it looks like an iOS-inspired switch. See the source code and the demo of https://github.com/tkent-google/std-switch for inspiration. All parts of the custom element are exposed via CSS [`::part()`](https://developer.mozilla.org/en-US/docs/Web/CSS/::part), so you can purely use CSS to create the look you want. 

Do you want to add the relevant styles to the demo, so others can use it?

**Comment by Haocen** [comment]
Hi @tomayac ,

Thanks for the response.
Last time I checked neither `input:checked + dark-mode-toggle::part(toggleLabel)::before` nor `dark-mode-toggle::part(toggleCheckbox):checked + dark-mode-toggle::part(toggleLabel)::before` selector is working for me in Chrome Version 107.0.5304.87 (Official Build) (x86_64) for Mac OS.

Could you please help me understand how I can style the pseudo element `dark-mode-toggle::part(toggleLabel)::before` when `dark-mode-toggle::part(toggleCheckbox)` element is checked?

Thanks.

**Comment by tomayac** [comment]
Here is a minimal example: https://furtive-frill-son.glitch.me/. See how the legend text is added via the CSS.

**Comment by Haocen** [comment]
> Here is a minimal example: https://furtive-frill-son.glitch.me/. See how the legend text is added via the CSS.

Yes I get how I can style individual parts however the more specific css selector `input:checked + dark-mode-toggle::part(toggleLabel)::before` & `dark-mode-toggle::part(toggleCheckbox):checked + dark-mode-toggle::part(toggleLabel)::before` is not working for me.

They are strickly needed for moving the thumb of the slider to right side when the checkbox is checked.

**Comment by Haocen** [comment]
Maybe I'm missing something but [this is what I'm seeing on the CLA page](https://cla.developers.google.com/about#:~:text=A%20Google%20account%20is%20required).
Screen Shot 2022-11-11 at 21 23 53

**Comment by Haocen** [comment]
I get it working by using `dark-mode-toggle[mode="dark"]::part(toggleLabel)::before` selector instead.
Not the most elegent way as it relies on JavaScript to update the `mode` attribute, then repaint & reflow the pseudo element instead of doing so within 1 single batch.
Anyway you're right, it is achievable without modifying the source code.
Feel free to close this PR.
I'll find some time for making another PR with minimal stylesheet to turn a toggle into slider.

**Comment by Haocen** [comment]
It seemed pseudo elements cannot inheret css variable properly if defined out of shadow-root.
A bug? Or maybe a _feature_.
undefined


Non-pseudo elements still getting the variable defined as expected.
defined

**Comment by tomayac** [comment]
My understanding is that we can close this in favor of #70.

**Pull request closed without merging**
